### PR TITLE
Product support guidance - English

### PR DESCRIPTION
**Pull request by jeffmaher**
# Summary | Résumé

Adds product support guidance for CDS product teams. These are not strict operating guidelines, but helpful suggestions. English translation only, French to follow in a separate pull request.

Trello: https://trello.com/c/gaOjQ55K

# Test instructions | Instructions pour tester la modification

See `_pages/en/product_support_guidance.md`, navigate via main navigation to "Product support guidance", or when running, go to `<base URL>/product_support_guidance`.

# Help requested | Aide requise

Feedback from Heads of Community and SRA team members have already been incorporated from the Google Doc version, but any last suggestions welcome this week via comments in the PR. Open for approval by @cmaczo on Monday.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

This can be a living doc, with modifications in the future. If there are any major overhauls suggested, they can go into future updates/PRs.

### CODE REVIEW

**Comment by jeffmaher** [comment]
@cds-snc/community-leads : Any suggestions before closing v1? Major suggestions should get prioritized for future updates of this living doc.

Note: I still have some formatting things to fix and will post back here when done. Open for content suggestions!

**Comment by jeffmaher** [comment]
Formatting fixes made!

**Review by wmoussa-gc — APPROVED** [review]

**Comment by jeffmaher** [comment]
Oh! One thing I didn't do yet was add links from the checklist items to the more verbose sections. Will do this ahead of Monday.

**Comment by jeffmaher** [comment]
Added links from checklist section to verbose sections.

**Comment by cmaczo** [comment]
Will review tomorrow.

**Pull request merged**
